# Generated by Django 4.1.1 on 2022-09-08 12:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Userdetail', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userdetails',
            new_name='Userdetail',
        ),
    ]
