# Generated by Django 4.1.1 on 2022-09-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
