# Generated by Django 4.1.1 on 2022-09-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0004_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
