# Generated by Django 4.1.1 on 2022-09-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='Pending', max_length=254)),
                ('provider_order_id', models.CharField(max_length=40)),
                ('payment_id', models.CharField(blank=True, max_length=36, null=True)),
                ('signature_id', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
