# Generated by Django 4.1.1 on 2022-09-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=1, max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='signature_id',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
