# Generated by Django 4.1.1 on 2022-11-25 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_payment_amount_alter_payment_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='message',
        ),
    ]
